name: update package version

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          node -e "const fs = require('fs'); 
          const commitHash = process.argv[1]; 
          const date = new Date(); 
          const formattedDate = (date.getMonth() + 1) + ' ' + date.getDate() + ' ' + date.getHours() + ':' + date.getMinutes(); 
          const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf-8')); 
          packageJson.version = commitHash.substring(0, 7) + '[' + formattedDate + ']'; 
          fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2));" $(git rev-parse HEAD)
        shell: bash
